# Generated by Django 4.2.1 on 2023-06-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%n/%d/'),
        ),
    ]
